AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  ffmpegTranscoder:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 1024
      Timeout: 600
      Role: 'arn:aws:iam::715604230268:role/lambda-ffmpeg'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: videos/
        BucketEvent2:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket2
            Events:
              - 's3:ObjectCreated:Put'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: input/
      Layers:
        - 'arn:aws:lambda:ap-south-1:715604230268:layer:aws-cli-layer:1'
        - 'arn:aws:lambda:ap-south-1:715604230268:layer:bc:3'
        - 'arn:aws:lambda:ap-south-1:715604230268:layer:ffmpeg:1'
  Bucket1:
    Type: 'AWS::S3::Bucket'
  Bucket2:
    Type: 'AWS::S3::Bucket'
